### ISSUE TITLE
Broken links to epub and txt versions of the book

### ISSUE THREAD

**Issue by jorpic** [abuseofnotation/time#11]
At the bottom of the page https://abuseofnotation.github.io/time/ there are two links to download the book as epub and as txt. Both lead to 404 page.

**Comment by abuseofnotation** [comment]
Haha, sorry, seeing this now, will fix them when I have time.

**Comment by abuseofnotation** [comment]
The book is now available for downloads on all formats on all book platforms: 
https://books2read.com/u/mY2NRP
It's free on Smashwords till the end of the month:
https://www.smashwords.com/books/view/1641587
